plugins:
  - jekyll-relative-links
  - jekyll-remote-theme

lsi: false
baseurl: "/senior-project-2026-2027-Evan-Zohrlaut"

remote_theme: pages-themes/cayman

title: EZ-Games
description: Senior Project